## Matrix inversion involves solving several linear equations simultaenously and is
## a computationally intensive call. It makes sense to cache the results of inverting
## a matrix.
##
## This R-script achieves this by providing two methods.
## "makeCacheMatrix" returns a special list that contains the matrix and the cached
## result.
## "cacheSolve" works on the list returned by the previous function and returns the
## cached inverse (or calculates it if required).
#####

## makeCacheMatrix(x)
# Parameters:
#     x       a matrix whose inverse might be needed repeatedly
#
# Returns:
#     a list of functions to get/set the matrix and the cache value
#
# Assumptions:
#     The matrix supplied is always invertible. There is no special error handling
#     for cases where this is not the case.
#
# This function creates a new environment for every matrix that's passed to it.
# This environment caches the inverse of the matrix.
# If you change the matrix with the set() function, the cache is set to NULL and 
# will have to be updated with the setinverse function.


makeCacheMatrix <- function(x = matrix()) {
    # Stores the inverse of the matrix
    cachedInverse <- NULL
    
    # Function to change the matrix (and clear the cache)
    set <- function(y) {
        x <<- y
        cachedInverse <<- NULL
    }
    
    # Returns the matrix
    get <- function() x
    
    # Updates the cache to the given inverse
    setinverse <- function(inv) cachedInverse <<- inv
    
    # Retries contents of the cache
    getinverse <- function() cachedInverse
    
    # Return value for makeCacheMatrix - a list of functions to operate with
    list(set=set, get=get, setinverse=setinverse, getinverse=getinverse)
}


## cachSolve(x)
# Parameters:
#    x         A cached-matrix (created using makeCacheMatrix)
#    ...       Any additional parameters to pass to "solve"
# 
# Returns:
#    The inverse of the given cached-matrix
#
# Assumptions:
#    The matrix supplied is always invertible. There is no special error handling
#    for cases where this is not the case.
#
# This function operates on cached matrices generated by makeCacheMatrix. 
cacheSolve <- function(x, ...) {
    # Fetch the cached result
    inverse <- x$getinverse()
    
    if(!is.null(inverse)) {
        # The cached result was not NULL - so it contains the inverse!
        message("Fetching cached inverse")
        
        # Skip the computation and return the result we fetched
        return(inverse)
    }
    
    # If we reach here (ie, the cached result was NULL), the cache doesn't contain
    # the inverse - so we need to calculate it.
    
    # Fetch the matrix contents
    matrix <- x$get()
    
    # Calculate the inverse of the matrix
    inverse <- solve(matrix, ...)
    
    # Update the cache - so that we won't have to solve again
    x$setinverse(inverse)
    
    # Return the inverse of x
    inverse
}